Fpass=350;          %Passband frequency
Fstop=16000;        %Stopband frequancy
Aband= 4;           %Passband ripple
Astop= 55;          %Stopband attentuation
Fs= 48000;          %Sampling frequancy

d = designfilt('lowpassiir', ...        
       'PassbandFrequency',Fpass, ...     
       'StopbandFrequency',Fstop, ...
       'PassbandRipple',Apass, ...          
       'StopbandAttenuation',Astop, ...
       'DesignMethod','butter', ...      
       'SampleRate',Fs)               
   fvtool(d)